POST http://localhost:3600/try-post
Content-Type: application/x-www-form-urlencoded

name=HAHAHA&age=87


###
POST http://localhost:3600/try-post
Content-Type: application/json

{
    "name": "鮭魚",
    "age": 30
}

# 最後一ㄍ不要逗點